export const STRINGS = {
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    saveChanges: 'Save changes',
    reset: 'Reset',
    applyFilters: 'Apply filters',
    pleaseWait: 'Please wait...',
  },
  auth: {
    appName: 'RescueOps',
    signInTitle: 'Sign in to your account',
    signUpTitle: 'Create your account',
    fullNameLabel: 'Full name',
    fullNamePlaceholder: 'Full name',
    emailLabel: 'Email',
    emailPlaceholder: 'you@example.org',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    missingFieldsError: 'Please fill all required fields.',
    ctaSignIn: 'Sign in',
    ctaCreateAccount: 'Create account',
    toggleToSignUp: "Don't have an account? Create one",
    toggleToSignIn: 'Have an account? Sign in',
    backToApp: 'Back to app',
    forgotPassword: 'Forgot password? Send reset email',
    resetEmailSent: 'If this email exists, a reset link was sent.',
    resetEmailFailed: 'Unable to send reset email.',
    demoHeading: 'Need a quick demo?',
    demoCta: 'Use mock data',
    genericContinueError: 'Unable to continue. Please try again.',
  },
  dogs: {
    title: 'Dogs',
    subtitle: 'Manage intake, medical status, transport, and adoption flow.',
    addDog: 'Add Dog',
    loadingDogs: 'Loading dogs...',
    emptyTitle: 'No dogs match the current filters.',
    resetFilters: 'Reset filters',
    deleteTitle: 'Delete Dog',
    deleteConfirmLabel: 'Delete',
    stageFilters: ['All', 'In Foster', 'Medical', 'Medical Hold', 'Transport', 'Available'],
    formStages: ['In Foster', 'Medical', 'Transport', 'Adopted'],
    mockCreateTitle: 'Create Dog (Mock)',
    mockEditTitle: 'Edit Dog (Mock)',
    mockSave: 'Save (mock)',
    mockSaveChanges: 'Save changes (mock)',
    mockSaved: 'Submitted (mock) — will be wired to Supabase later.',
    mockCreatedAlertTitle: 'Mock submit',
    mockCreatedAlertBody: 'Dog saved (mock). This will be wired to Supabase in Phase 2.',
    mockUpdatedAlertBody: 'Dog updated (mock). Supabase wiring comes in Phase 2.',
    form: {
      nameLabel: 'Name',
      namePlaceholder: 'Dog name',
      stageLabel: 'Stage',
      stagePlaceholder: 'In Foster, Medical...',
      locationLabel: 'Location',
      locationPlaceholder: 'City / region',
      responsibleLabel: 'Responsible Person',
      responsiblePlaceholder: 'Optional',
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Personality, behavior, background',
      stageOptionsHelperPrefix: 'Options:',
    },
    validation: {
      nameRequired: 'Name is required',
      stageRequired: 'Stage is required',
      locationRequired: 'Location is required',
      descriptionRequired: 'Description is required',
    },
  },
  people: {
    title: 'People & Homes',
    subtitleUsers: 'App users (memberships)',
    subtitleContacts: 'Contacts (including offline fosters/homes).',
    datasetContacts: 'Contacts',
    datasetUsers: 'App users',
    createContact: 'Create contact',
  },
  transports: {
    title: 'Transports',
    subtitle: 'View transport events or transporters assigned to your org.',
    newTransport: 'New transport',
    loadingTransporters: 'Loading transporters...',
    loadingTransports: 'Loading transports...',
    emptyTransporters: 'No transporters found for this org.',
    emptyTransports: 'No transports scheduled for this org.',
  },
  calendar: {
    title: 'Calendar',
    subtitle: 'Schedule across medical, transports, and quarantine windows.',
    syncNow: 'Sync notifications',
    syncing: 'Syncing notifications...',
    empty: 'No events scheduled in this range.',
    viewDay: 'Day',
    viewWeek: 'Week',
    viewMonth: 'Month',
    today: 'Today',
    previous: 'Prev',
    next: 'Next',
    loading: 'Loading calendar...',
    filters: {
      searchPlaceholder: 'Search events, dogs, or locations...',
      typeLabel: 'Types',
      dogLabel: 'Dog',
      contactLabel: 'Contact / Foster',
      stageLabel: 'Stage',
      anyStage: 'Any',
      dateRangeLabel: 'Date range',
      startPlaceholder: 'Start (YYYY-MM-DD)',
      endPlaceholder: 'End (YYYY-MM-DD)',
      clear: 'Clear filters',
    },
    addEvent: {
      cta: 'Add Event',
      general: 'General event',
      medical: 'Log medical record',
      transport: 'Schedule transport',
      titleLabel: 'Title',
      startLabel: 'Start',
      endLabel: 'End',
      locationLabel: 'Location',
      typeLabel: 'Type',
      datetimePlaceholder: 'YYYY-MM-DDTHH:mm',
      reminderOffsetLabel: 'Reminder offset (minutes)',
      linkDogLabel: 'Link to dog (optional)',
      createSuccess: 'Event created.',
      createError: 'Unable to create event.',
      openTransports: 'Open transport scheduler',
      openDogs: 'Open dogs directory',
      validation: {
        missingOrg: 'Select an organization before creating an event.',
        invalidDates: 'Enter valid start and end times.',
        endBeforeStart: 'End time must be after start.',
      },
    },
    detail: {
      heading: 'Event details',
      reminders: 'Reminders',
      noReminders: 'No reminders scheduled for this event.',
      openLink: 'Open linked record',
      statusLabel: 'Status',
      whenLabel: 'When',
    },
    typeLabels: {
      transport: 'Transport',
      medical: 'Medical',
      quarantine: 'Quarantine',
      general: 'General',
      system_task: 'System task',
      finance: 'Finance',
      external: 'External',
    },
  },
  notifications: {
    permissionMissing: 'Notification permission is required to schedule reminders.',
    webNotice: 'Web uses inline feedback; local notifications are mobile-only.',
    noOrg: 'No active organization to sync notifications.',
    syncFailure: 'Failed to sync notifications.',
  },
  filters: {
    searchPlaceholderGeneric: 'Search by name, ID, or foster...',
    advancedFiltersTitle: 'Advanced Filters',
    locationLabel: 'Location',
    locationPlaceholder: 'e.g. Shelter HQ or Vet',
    responsibleLabel: 'Responsible person',
    responsiblePlaceholder: 'e.g. Maria Garcia',
    updatedAfter: 'Updated after',
    updatedBefore: 'Updated before',
    datePlaceholder: 'YYYY-MM-DD',
    hasAlerts: 'Has alerts',
    hasAlertsDescription: 'Only show dogs with alerts',
    filtersButton: 'Filters',
    noFilters: 'No filters yet.',
  },
} as const;

export function formatDogDeleteMessage(dogName?: string | null) {
  const name = dogName?.trim() ? `"${dogName.trim()}"` : 'this dog';
  return `Are you sure you want to delete ${name}? This action can be undone by an administrator.`;
}

export function formatNotificationSyncSuccess(days: number) {
  return `Notifications synced for the next ${days} days.`;
}
